### ISSUE TITLE
可以动态修改模拟器的IMEI吗？？

### ISSUE THREAD

**Issue by liguangze** [ReimuNotMoe/libIMEI#1]
可以动态修改模拟器的IMEI吗？？

**Comment by ReimuNotMoe** [comment]
你是说Android模拟器吗？

很多Android模拟器自带修改IMEI的功能。如果你在使用的没有，可以尝试使用Xposed及其模块。

此项目是一个可以生成/校验IMEI的库。如果你需要一个能直接使用的App，可以去看我的 IMEIGeneratorApp项目。
